package com.stacksync.desktop.gui.sharing;

import com.stacksync.desktop.config.Config;
import com.stacksync.desktop.encryption.BasicEncryption;
import com.stacksync.desktop.config.Folder;
import com.stacksync.desktop.config.profile.Profile;
import com.stacksync.desktop.db.DatabaseHelper;
import com.stacksync.desktop.exceptions.ConfigException;
import com.stacksync.desktop.gui.error.ErrorMessage;
import com.stacksync.desktop.syncserver.Server;
import com.stacksync.desktop.util.FileUtil;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.JFrame;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class UnsharePanel extends javax.swing.JPanel implements DocumentListener, ItemListener {

    private static final Config config = Config.getInstance();
    private ResourceBundle resourceBundle;
    
    private JFrame frame;
    private File folderSelected;
    
    public final String lock = "";
    
    private List<String> emails;
    /**
     * Creates new form SharePanel
     */
    public UnsharePanel(JFrame frame) {
        
        super();
        
        emails = new ArrayList<String>();
        
        this.resourceBundle = config.getResourceBundle();
        this.frame = frame;
        initComponents();
        
        //this.lblMail.setText(resourceBundle.getString("unshare_panel_email"));
        //this.lblFolder.setText(resourceBundle.getString("unshare_panel_folder"));
        //this.cancelButton.setText(resourceBundle.getString("wizard_cancel"));
        //this.unshareButton.setText(resourceBundle.getString("unshare_button_share"));
        this.unshareButton.setEnabled(false);
        //this.browseButton.setText(resourceBundle.getString("fpw_simple_browse")); 
        
        this.emailField.getDocument().addDocumentListener(this);
        this.folderNameField.getDocument().addDocumentListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailField = new javax.swing.JTextField();
        lblMail = new javax.swing.JLabel();
        lblFolder = new javax.swing.JLabel();
        folderNameField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        unshareButton = new javax.swing.JButton();
        browseButton = new javax.swing.JButton();

        lblMail.setText("__E-mail:");

        lblFolder.setText("__Folder name:");

        folderNameField.setEditable(false);

        cancelButton.setText("__Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        unshareButton.setText("__Unshare");
        unshareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unshareButtonActionPerformed(evt);
            }
        });

        browseButton.setText("__Browse");
        browseButton.setName("browseButton"); // NOI18N
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFolder)
                    .addComponent(lblMail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(folderNameField)
                    .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(browseButton)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(unshareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(folderNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFolder)
                    .addComponent(browseButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unshareButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void unshareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unshareButtonActionPerformed

        if (this.emailField.getText().isEmpty() || this.folderNameField.getText().isEmpty()) {
            return;
        }
        
        Profile profile = config.getProfile();
        Server server = profile.getServer();
        
        List<String> emailsList;
        try {
            emailsList = parseEmails();
        } catch (IOException ex) {
            ErrorMessage.showMessage(this, "Error", "Verify email accounts.");
            return;
        }    

        DatabaseHelper db = DatabaseHelper.getInstance();

        if (this.folderSelected == null) {
            ErrorMessage.showMessage(this, "Error", "No folder selected!");
            return;
        }
            
        this.frame.setVisible(false);
            
        synchronized(lock){
            this.lock.notify();
        }
        
    }//GEN-LAST:event_unshareButtonActionPerformed

    public List<String> getEmails(){
        return emails;
    }
    
    private List<String> parseEmails() throws IOException {
        
        String emailsStr = this.emailField.getText();
        emailsStr = emailsStr.replaceAll("\\s", "");    // Remove whitespaces
        List<String> emailsList = Arrays.asList(emailsStr.split(","));   // Split it
        
        for (String email : emailsList) {
            // Check if email is correct
            if (!isCorrect(email)) {
                throw new IOException("Incorrect mail.");
            }
            
            emails.add(email);
        }
        
        // All mails are correct! =)
        return emails;
    }
    
    private boolean isCorrect(String mail) {
        
        if (!mail.contains("@") || !mail.contains(".")) {
            return false;
        }
        
        // Add here other filters (special characters...)
        
        return true;
    }
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.frame.setVisible(false);
        synchronized(lock){
            this.lock.notify();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed

        File file = FileUtil.showBrowseDirectoryDialog();
        if (file != null && !file.getPath().equals("")) {
            
            Profile profile = config.getProfile();
            Folder folder = profile.getFolder();
            String rootFolderPath = folder.getLocalFile().getAbsolutePath();
            String sharedFolderPath = file.getAbsolutePath();
            
            if (!sharedFolderPath.contains(rootFolderPath) || sharedFolderPath.equals(rootFolderPath)) {
                ErrorMessage.showMessage(this, "Error", "Incorrect folder.");
                return;
            }
            
            this.folderNameField.setText(file.getAbsolutePath());
            this.folderSelected = file;
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField folderNameField;
    private javax.swing.JLabel lblFolder;
    private javax.swing.JLabel lblMail;
    private javax.swing.JButton unshareButton;
    // End of variables declaration//GEN-END:variables

    /*
     * Functions to enable/disable dynamically the share button
     */
    @Override
    public void insertUpdate(DocumentEvent e) {
        setEnableShareButton();
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        setEnableShareButton();
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        setEnableShareButton();
    }
    
    private void setEnableShareButton() {
        if (this.emailField.getText().equals("") ||
                this.folderNameField.getText().equals("")) {
            this.unshareButton.setEnabled(false);
        } else {
            this.unshareButton.setEnabled(true);
            getRootPane().setDefaultButton(this.unshareButton);
        }
    }

    public File getFolderSelected() {
        return this.folderSelected;
    }
    
    @Override
    public void itemStateChanged(ItemEvent e) {
       //Nothing to do
    }
}
