/*
 * Syncany, www.syncany.org
 * Copyright (C) 2011 Philipp C. Heckel <philipp.heckel@gmail.com> 
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.stacksync.desktop.connection.plugins.swift_dev;

import com.stacksync.desktop.connection.plugins.swift.SwiftConnection;
import com.stacksync.desktop.connection.plugins.swift.SwiftConfigPanelFactory;
import com.stacksync.desktop.connection.plugins.ConfigPanel;
import com.stacksync.desktop.connection.plugins.TransferManager;
import com.stacksync.desktop.exceptions.StorageConnectException;
import com.stacksync.desktop.gui.error.ErrorMessage;

/**
 *
 * @author Philipp C. Heckel <philipp.heckel@gmail.com>
 */
public class SwiftDevConfigPanel extends ConfigPanel {
	
    public SwiftDevConfigPanel(SwiftConnection connection) {
        super(connection);
        initComponents();	
        
        /// setting text ///                        
        jLabel1.setText(resourceBundle.getString("ftpc_username"));
        jLabel2.setText(resourceBundle.getString("ftpc_password"));  
        
        txtAuthUrl.setText(SwiftConfigPanelFactory.AUTH_URL);
    }

    @Override
    public void load() {        
        String userName = getConnection().getUsername();
        
        if(userName.contains(":")){
            userName = userName.split(":")[0];
        }
        
        txtUsername.setText(userName);
        txtApiKey.setText(getConnection().getApiKey());
        txtContainerName.setText(getConnection().getContainer());
        txtAuthUrl.setText(getConnection().getAuthUrl());        
    }

    @Override
    public void save() {
        String userName = getUserName();
        
        getConnection().setUsername(userName + ":" + userName);
        getConnection().setApiKey(getPassword());
        getConnection().setContainer(getContainerName());
        getConnection().setAuthUrl(getAuthUrl());
    }

    @Override
    public SwiftConnection getConnection() {
        return (SwiftConnection) super.getConnection();
    }       
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        txtApiKey = new javax.swing.JPasswordField();
        txtContainerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAuthUrl = new javax.swing.JTextField();

        txtUsername.setName("txtUsername"); // NOI18N

        txtApiKey.setName("txtApiKey"); // NOI18N

        txtContainerName.setName("txtContainerName"); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Container Name:");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Username:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("API Key:");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Auth URL:");
        jLabel4.setName("jLabel4"); // NOI18N

        txtAuthUrl.setName("txtAuthUrl"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAuthUrl)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(txtApiKey, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(txtContainerName, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApiKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContainerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtAuthUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtApiKey;
    private javax.swing.JTextField txtAuthUrl;
    private javax.swing.JTextField txtContainerName;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clean() {
        txtUsername.setText("");
        txtApiKey.setText("");
        txtContainerName.setText(SwiftConfigPanelFactory.CONTAINER);
        txtAuthUrl.setText(SwiftConfigPanelFactory.AUTH_URL);
    }

    private String getUserName(){
        return txtUsername.getText().trim();
    }
    
    private String getPassword(){
        return new String(txtApiKey.getPassword());
    }
    
    private String getContainerName(){
        return txtContainerName.getText().trim();
    }
    
    private String getAuthUrl(){
        return txtAuthUrl.getText().trim();
    }
        
    @Override
    public boolean check() {
        String userName = getUserName();
        String password = getPassword();
        String container = getContainerName();
        String authUrl = getAuthUrl();
        
        // check UserName
        if(userName.isEmpty()){
            ErrorMessage.showMessage(this, "Error", "The username is empty.");
            return false;
        } else{        
            if(userName.contains(":") || userName.contains("-") || userName.contains("_") || 
               userName.contains("/") || userName.contains("\\")){
               ErrorMessage.showMessage(this, "Error", "The username have invalid characters(:-_/\\)");
               return false;
            }
        }

        // check Password
        if(password.isEmpty()){            
            ErrorMessage.showMessage(this, "Error", "The password is empty.");
            return false;
        }
        
        //check Container
        if(container.isEmpty()){
            ErrorMessage.showMessage(this, "Error", "The password container is empty.");            
            return false;
        }
        
        // check AuthUrl
        if(authUrl.isEmpty()){
            ErrorMessage.showMessage(this, "Error", "The auth url is empty.");
            return false;
        } else {            
            //ping to host
            SwiftConnection connection = new SwiftConnection();
            connection.setApiKey(password);
            connection.setAuthUrl(authUrl);
            connection.setContainer("");
            connection.setUsername(userName + ":" + userName);
            
            TransferManager transfer = connection.createTransferManager();
            try {           
                transfer.connect();
            } catch (StorageConnectException ex) {                
                ErrorMessage.showMessage(this, "Error", "the Auth url is incorrect. Host is not reachable.\n" + ex.getMessage());
                return false;
            }            
        }
                
        return true;
    }
}