/*
 * Syncany, www.syncany.org
 * Copyright (C) 2011 Philipp C. Heckel <philipp.heckel@gmail.com> 
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.stacksync.desktop.gui.error;

import java.util.ResourceBundle;
import javax.swing.JFrame;
import org.apache.log4j.Logger;
import com.stacksync.desktop.Stacksync;
import com.stacksync.desktop.config.Config;
import com.stacksync.desktop.logging.RemoteLogs;
import com.stacksync.desktop.util.StringUtil;

/**
 *
 * @author pheckel
 */
public class ErrorDialog extends javax.swing.JDialog {
    private final Logger logger = Logger.getLogger(ErrorDialog.class.getName());
    private final Config config = Config.getInstance();
    private ResourceBundle resourceBundle;
    private Exception errorReportException;
    private ErrorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        resourceBundle = config.getResourceBundle();
        initComponents();

        setTexts();
        lblSent.setVisible(false);
        getRootPane().setDefaultButton(btnReport);
        setLocationRelativeTo(null);
    }
    
    private void setTexts() {
        this.btnQuit.setText(resourceBundle.getString("errd_quit_stacksync"));
        this.btnReport.setText(resourceBundle.getString("errd_report_crash"));
        this.btnRestart.setText(resourceBundle.getString("errd_restart_stacksync"));
        this.titleLbl.setText(resourceBundle.getString("errd_message"));
        this.descriptionLbl.setText(resourceBundle.getString("errd_stacksync_crashed"));
        this.description2Lbl.setText(resourceBundle.getString("errd_report_bug"));
        this.commentsLbl.setText(resourceBundle.getString("errd_comments"));
        this.lblSent.setText(resourceBundle.getString("errd_report_was_sent"));
    }
    
    private void setThrowable(Exception e) {	
    txtError.setText(StringUtil.getStackTrace(e));
    errorReportException = e;
    }
    private Exception getException(){
        return errorReportException;
    }
    
    public static void showDialog(Exception e) {
        ErrorDialog dialog = new ErrorDialog(new JFrame(), true);
	
        dialog.setThrowable(e);	
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(2);
            }
        });	

        dialog.setVisible(true);        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtError = new javax.swing.JTextArea();
        btnRestart = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        description2Lbl = new javax.swing.JLabel();
        descriptionLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComments = new javax.swing.JTextArea();
        commentsLbl = new javax.swing.JLabel();
        lblSent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtError.setColumns(20);
        txtError.setRows(5);
        txtError.setName("txtError"); // NOI18N
        jScrollPane1.setViewportView(txtError);

        btnRestart.setText("__Restart Stacksync");
        btnRestart.setName("btnRestart"); // NOI18N
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        btnReport.setText("__Report Crash");
        btnReport.setName("btnReport"); // NOI18N
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnQuit.setText("__Quit Stacksync");
        btnQuit.setName("btnQuit"); // NOI18N
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        description2Lbl.setText("__You can help fixing this bug by sending us the error messge below. Just click 'Report Bug'.");
        description2Lbl.setName("description2Lbl"); // NOI18N

        descriptionLbl.setText("__We are very sorry, but it seems that Stacksync crashed. Find details below. ");
        descriptionLbl.setName("descriptionLbl"); // NOI18N

        titleLbl.setFont(titleLbl.getFont().deriveFont(titleLbl.getFont().getStyle() | java.awt.Font.BOLD, titleLbl.getFont().getSize()+2));
        titleLbl.setText("__An Error occurred.");
        titleLbl.setName("titleLbl"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        txtComments.setColumns(20);
        txtComments.setRows(5);
        txtComments.setName("txtComments"); // NOI18N
        jScrollPane2.setViewportView(txtComments);

        commentsLbl.setText("__Your Comments:");
        commentsLbl.setName("commentsLbl"); // NOI18N

        lblSent.setFont(lblSent.getFont().deriveFont(lblSent.getFont().getStyle() | java.awt.Font.BOLD));
        lblSent.setText("__Your report has been sent.");
        lblSent.setName("lblSent"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                    .addComponent(titleLbl, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLbl, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description2Lbl, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                    .addComponent(commentsLbl, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(description2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(commentsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestart)
                    .addComponent(btnReport)
                    .addComponent(btnQuit)
                    .addComponent(lblSent))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(2);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        dispose();
        Stacksync.start();
    }//GEN-LAST:event_btnRestartActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed

        btnReport.setText(resourceBundle.getString("errd_sending"));
        btnReport.setEnabled(false);

        new Thread(new Runnable() {
            @Override
            public void run() {
                logger.error("User message: "+txtComments.getText(), getException());
                RemoteLogs.getInstance().sendLog(getException());                      
            }
        }, "SendCrashRep").start();
    }//GEN-LAST:event_btnReportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnRestart;
    private javax.swing.JLabel commentsLbl;
    private javax.swing.JLabel description2Lbl;
    private javax.swing.JLabel descriptionLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSent;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextArea txtComments;
    private javax.swing.JTextArea txtError;
    // End of variables declaration//GEN-END:variables

}